import { StyleSheet } from "react-native";

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  title: {
    fontSize: 22,
    fontWeight: "800",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  grid: {
    paddingBottom: 120,
    gap: 12,
  },
  columnWrapper: {
    gap: 12,
  },
  card: {
    flex: 1,
    borderRadius: 20,
    borderWidth: 1,
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  image: {
    width: "100%",
    aspectRatio: 1,
  },
  cardBody: {
    padding: 12,
    gap: 6,
    minHeight: 86,
  },
  productName: {
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 16,
    minHeight: 32,
  },
  price: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  addButton: {
    marginTop: 6,
    paddingVertical: 7,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    marginBottom: 10,
  },
  addButtonText: {
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  cta: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
  },
  ctaText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 12,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  toast: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 20,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: "center",
    shadowColor: "#000000",
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 2,
  },
  toastText: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
});
